
###
GET  http://localhost:3000/api/settings?context=cardapio-pizza-taglio

###
POST  http://localhost:3000/api/settings
Content-type: application/json


{
    "action": "cardapio-pizza-taglio-upsert",
    "value": "cucu",
    "secret": "fOD19KP7zZaloS3nMyux3qqI8ABihL3c"
}

###
GET http://localhost:3000/api/orcamento
x-api-key: 3PjN!u9g@r5XzE1fQw7H

###
GET https://www.amodomio.com.br/api/orcamento
x-api-key: 3PjN!u9g@r5XzE1fQw7H